services:
  nxad-challenge-a:
    build:
      context: ../sample-web
    container_name: nxad-challenge-a
    restart: unless-stopped
    environment:
      TEAM_NAME: "a"
      SERVICE_NAME: "sample-web"
      FLAG: "9787b288-fba3-4aa1-8c31-c5dc046fd7a5"
      SSH_USER: "team"
      SSH_PASSWORD: "4d7ec14adb73"
    ports:
      - "9000:8000"
      - "9022:22"
    networks:
      - nxad-challenges

  nxad-challenge-b:
    build:
      context: ../sample-web
    container_name: nxad-challenge-b
    restart: unless-stopped
    environment:
      TEAM_NAME: "b"
      SERVICE_NAME: "sample-web"
      FLAG: "e5f6b21a-06a7-46d4-8b6a-4bac6a6cd9e8"
      SSH_USER: "team"
      SSH_PASSWORD: "e861b0b10e60"
    ports:
      - "9001:8000"
      - "9023:22"
    networks:
      - nxad-challenges

networks:
  nxad-challenges:
    driver: bridge
